// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_postgres_cluster

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/listvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64default"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"regexp"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func PostgresClusterResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"cluster_id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The unique identifier of a cluster.",
				MarkdownDescription: "The unique identifier of a cluster.",
			},
			"created_on": schema.StringAttribute{
				Computed:            true,
				Description:         "When the cluster has been created.",
				MarkdownDescription: "When the cluster has been created.",
			},
			"extensions": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"name": schema.StringAttribute{
							Required:            true,
							Description:         "The name of the extension.",
							MarkdownDescription: "The name of the extension.",
							Validators: []validator.String{
								stringvalidator.OneOf(
									"TIMESCALEDB",
									"VECTOR",
								),
							},
						},
					},
					CustomType: ExtensionsType{
						ObjectType: types.ObjectType{
							AttrTypes: ExtensionsValue{}.AttributeTypes(ctx),
						},
					},
				},
				Optional:            true,
				Computed:            true,
				Description:         "List of extensions on the cluster.",
				MarkdownDescription: "List of extensions on the cluster.",
				Validators: []validator.List{
					listvalidator.SizeAtMost(50),
					listvalidator.UniqueValues(),
				},
			},
			"full_version": schema.StringAttribute{
				Computed:            true,
				Description:         "The version of postgresql.",
				MarkdownDescription: "The version of postgresql.",
			},
			"host": schema.StringAttribute{
				Computed:            true,
				Description:         "Public address to be used for connecting to the PostgreSQL cluster from outside or by external clients.",
				MarkdownDescription: "Public address to be used for connecting to the PostgreSQL cluster from outside or by external clients.",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "A cluster unique identifier.",
				MarkdownDescription: "A cluster unique identifier.",
			},
			"major_version": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The version of postgresql to create a cluster.",
				MarkdownDescription: "The version of postgresql to create a cluster.",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"16",
						"17",
						"18",
					),
				},
				Default: stringdefault.StaticString("18"),
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "A PostgreSQL cluster name.",
				MarkdownDescription: "A PostgreSQL cluster name.",
				Validators: []validator.String{
					stringvalidator.LengthBetween(3, 63),
					stringvalidator.RegexMatches(regexp.MustCompile("^[a-zA-Z0-9]+(?:[-_][a-zA-Z0-9]+)*$"), ""),
				},
			},
			"node_configuration": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"memory_size_gi_b": schema.Int64Attribute{
						Required:            true,
						Description:         "The allocated memory size, in GiB.",
						MarkdownDescription: "The allocated memory size, in GiB.",
						Validators: []validator.Int64{
							int64validator.Between(1, 3),
						},
					},
					"vcpu_count": schema.Int64Attribute{
						Required:            true,
						Description:         "The number of Virtual CPU provisioned.",
						MarkdownDescription: "The number of Virtual CPU provisioned.",
						Validators: []validator.Int64{
							int64validator.Between(1, 3),
						},
					},
				},
				CustomType: NodeConfigurationType{
					ObjectType: types.ObjectType{
						AttrTypes: NodeConfigurationValue{}.AttributeTypes(ctx),
					},
				},
				Required:            true,
				Description:         "The configuration used to provision the cluster nodes.",
				MarkdownDescription: "The configuration used to provision the cluster nodes.",
			},
			"port": schema.Int64Attribute{
				Computed:            true,
				Description:         "TCP port on which the PostgreSQL server is exposed for connections",
				MarkdownDescription: "TCP port on which the PostgreSQL server is exposed for connections",
			},
			"replica_count": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Number of replicas to maintain for high availability. This number does not include the primary instance. The actual distribution across NumSpot subregions depends on available resources.",
				MarkdownDescription: "Number of replicas to maintain for high availability. This number does not include the primary instance. The actual distribution across NumSpot subregions depends on available resources.",
				Validators: []validator.Int64{
					int64validator.Between(0, 2),
				},
				Default: int64default.StaticInt64(0),
			},
			"status": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"message": schema.StringAttribute{
						Computed:            true,
						Description:         "Detailed information regarding the current state of the cluster.",
						MarkdownDescription: "Detailed information regarding the current state of the cluster.",
					},
					"state": schema.StringAttribute{
						Computed:            true,
						Description:         "The current state of the cluster.",
						MarkdownDescription: "The current state of the cluster.",
					},
				},
				CustomType: StatusType{
					ObjectType: types.ObjectType{
						AttrTypes: StatusValue{}.AttributeTypes(ctx),
					},
				},
				Computed:            true,
				Description:         "The status of the cluster.",
				MarkdownDescription: "The status of the cluster.",
			},
			"user": schema.StringAttribute{
				Required:            true,
				Description:         "The name of the user on the cluster.",
				MarkdownDescription: "The name of the user on the cluster.",
				Validators: []validator.String{
					stringvalidator.LengthBetween(3, 63),
					stringvalidator.RegexMatches(regexp.MustCompile("^[a-zA-Z0-9]+(?:[-_][a-zA-Z0-9]+)*$"), ""),
				},
			},
			"visibility": schema.StringAttribute{
				Required:            true,
				Description:         "Cluster exposition method.",
				MarkdownDescription: "Cluster exposition method.",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"EXTERNAL",
						"INTERNAL",
					),
				},
			},
			"volume": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"size_gi_b": schema.Int64Attribute{
						Required:            true,
						Description:         "The size of the volume in GiB.",
						MarkdownDescription: "The size of the volume in GiB.",
						Validators: []validator.Int64{
							int64validator.Between(1, 14901),
						},
					},
					"type": schema.StringAttribute{
						Required:            true,
						Description:         "The storage volume type.",
						MarkdownDescription: "The storage volume type.",
						Validators: []validator.String{
							stringvalidator.OneOf(
								"GP2",
								"IO1",
								"STANDARD",
							),
						},
					},
				},
				CustomType: VolumeType{
					ObjectType: types.ObjectType{
						AttrTypes: VolumeValue{}.AttributeTypes(ctx),
					},
				},
				Required:            true,
				Description:         "Configuration for a PostgreSQL storage volume.",
				MarkdownDescription: "Configuration for a PostgreSQL storage volume.",
			},
		},
	}
}

type PostgresClusterModel struct {
	ClusterId         types.String           `tfsdk:"cluster_id"`
	CreatedOn         types.String           `tfsdk:"created_on"`
	Extensions        types.List             `tfsdk:"extensions"`
	FullVersion       types.String           `tfsdk:"full_version"`
	Host              types.String           `tfsdk:"host"`
	Id                types.String           `tfsdk:"id"`
	MajorVersion      types.String           `tfsdk:"major_version"`
	Name              types.String           `tfsdk:"name"`
	NodeConfiguration NodeConfigurationValue `tfsdk:"node_configuration"`
	Port              types.Int64            `tfsdk:"port"`
	ReplicaCount      types.Int64            `tfsdk:"replica_count"`
	Status            StatusValue            `tfsdk:"status"`
	User              types.String           `tfsdk:"user"`
	Visibility        types.String           `tfsdk:"visibility"`
	Volume            VolumeValue            `tfsdk:"volume"`
}

var _ basetypes.ObjectTypable = ExtensionsType{}

type ExtensionsType struct {
	basetypes.ObjectType
}

func (t ExtensionsType) Equal(o attr.Type) bool {
	other, ok := o.(ExtensionsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ExtensionsType) String() string {
	return "ExtensionsType"
}

func (t ExtensionsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ExtensionsValue{
		Name:  nameVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewExtensionsValueNull() ExtensionsValue {
	return ExtensionsValue{
		state: attr.ValueStateNull,
	}
}

func NewExtensionsValueUnknown() ExtensionsValue {
	return ExtensionsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewExtensionsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ExtensionsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ExtensionsValue Attribute Value",
				"While creating a ExtensionsValue value, a missing attribute value was detected. "+
					"A ExtensionsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ExtensionsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ExtensionsValue Attribute Type",
				"While creating a ExtensionsValue value, an invalid attribute value was detected. "+
					"A ExtensionsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ExtensionsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ExtensionsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ExtensionsValue Attribute Value",
				"While creating a ExtensionsValue value, an extra attribute value was detected. "+
					"A ExtensionsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ExtensionsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewExtensionsValueUnknown(), diags
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewExtensionsValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	if diags.HasError() {
		return NewExtensionsValueUnknown(), diags
	}

	return ExtensionsValue{
		Name:  nameVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewExtensionsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ExtensionsValue {
	object, diags := NewExtensionsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewExtensionsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ExtensionsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewExtensionsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewExtensionsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewExtensionsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewExtensionsValueMust(ExtensionsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ExtensionsType) ValueType(ctx context.Context) attr.Value {
	return ExtensionsValue{}
}

var _ basetypes.ObjectValuable = ExtensionsValue{}

type ExtensionsValue struct {
	Name  basetypes.StringValue `tfsdk:"name"`
	state attr.ValueState
}

func (v ExtensionsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 1)

	var val tftypes.Value
	var err error

	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 1)

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ExtensionsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ExtensionsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ExtensionsValue) String() string {
	return "ExtensionsValue"
}

func (v ExtensionsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"name": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"name": v.Name,
		})

	return objVal, diags
}

func (v ExtensionsValue) Equal(o attr.Value) bool {
	other, ok := o.(ExtensionsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	return true
}

func (v ExtensionsValue) Type(ctx context.Context) attr.Type {
	return ExtensionsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ExtensionsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"name": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = NodeConfigurationType{}

type NodeConfigurationType struct {
	basetypes.ObjectType
}

func (t NodeConfigurationType) Equal(o attr.Type) bool {
	other, ok := o.(NodeConfigurationType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t NodeConfigurationType) String() string {
	return "NodeConfigurationType"
}

func (t NodeConfigurationType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	memorySizeGiBAttribute, ok := attributes["memory_size_gi_b"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`memory_size_gi_b is missing from object`)

		return nil, diags
	}

	memorySizeGiBVal, ok := memorySizeGiBAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`memory_size_gi_b expected to be basetypes.Int64Value, was: %T`, memorySizeGiBAttribute))
	}

	vcpuCountAttribute, ok := attributes["vcpu_count"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`vcpu_count is missing from object`)

		return nil, diags
	}

	vcpuCountVal, ok := vcpuCountAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`vcpu_count expected to be basetypes.Int64Value, was: %T`, vcpuCountAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return NodeConfigurationValue{
		MemorySizeGiB: memorySizeGiBVal,
		VcpuCount:     vcpuCountVal,
		state:         attr.ValueStateKnown,
	}, diags
}

func NewNodeConfigurationValueNull() NodeConfigurationValue {
	return NodeConfigurationValue{
		state: attr.ValueStateNull,
	}
}

func NewNodeConfigurationValueUnknown() NodeConfigurationValue {
	return NodeConfigurationValue{
		state: attr.ValueStateUnknown,
	}
}

func NewNodeConfigurationValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (NodeConfigurationValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing NodeConfigurationValue Attribute Value",
				"While creating a NodeConfigurationValue value, a missing attribute value was detected. "+
					"A NodeConfigurationValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("NodeConfigurationValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid NodeConfigurationValue Attribute Type",
				"While creating a NodeConfigurationValue value, an invalid attribute value was detected. "+
					"A NodeConfigurationValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("NodeConfigurationValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("NodeConfigurationValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra NodeConfigurationValue Attribute Value",
				"While creating a NodeConfigurationValue value, an extra attribute value was detected. "+
					"A NodeConfigurationValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra NodeConfigurationValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewNodeConfigurationValueUnknown(), diags
	}

	memorySizeGiBAttribute, ok := attributes["memory_size_gi_b"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`memory_size_gi_b is missing from object`)

		return NewNodeConfigurationValueUnknown(), diags
	}

	memorySizeGiBVal, ok := memorySizeGiBAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`memory_size_gi_b expected to be basetypes.Int64Value, was: %T`, memorySizeGiBAttribute))
	}

	vcpuCountAttribute, ok := attributes["vcpu_count"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`vcpu_count is missing from object`)

		return NewNodeConfigurationValueUnknown(), diags
	}

	vcpuCountVal, ok := vcpuCountAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`vcpu_count expected to be basetypes.Int64Value, was: %T`, vcpuCountAttribute))
	}

	if diags.HasError() {
		return NewNodeConfigurationValueUnknown(), diags
	}

	return NodeConfigurationValue{
		MemorySizeGiB: memorySizeGiBVal,
		VcpuCount:     vcpuCountVal,
		state:         attr.ValueStateKnown,
	}, diags
}

func NewNodeConfigurationValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) NodeConfigurationValue {
	object, diags := NewNodeConfigurationValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewNodeConfigurationValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t NodeConfigurationType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewNodeConfigurationValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewNodeConfigurationValueUnknown(), nil
	}

	if in.IsNull() {
		return NewNodeConfigurationValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewNodeConfigurationValueMust(NodeConfigurationValue{}.AttributeTypes(ctx), attributes), nil
}

func (t NodeConfigurationType) ValueType(ctx context.Context) attr.Value {
	return NodeConfigurationValue{}
}

var _ basetypes.ObjectValuable = NodeConfigurationValue{}

type NodeConfigurationValue struct {
	MemorySizeGiB basetypes.Int64Value `tfsdk:"memory_size_gi_b"`
	VcpuCount     basetypes.Int64Value `tfsdk:"vcpu_count"`
	state         attr.ValueState
}

func (v NodeConfigurationValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["memory_size_gi_b"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["vcpu_count"] = basetypes.Int64Type{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.MemorySizeGiB.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["memory_size_gi_b"] = val

		val, err = v.VcpuCount.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["vcpu_count"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v NodeConfigurationValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v NodeConfigurationValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v NodeConfigurationValue) String() string {
	return "NodeConfigurationValue"
}

func (v NodeConfigurationValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"memory_size_gi_b": basetypes.Int64Type{},
		"vcpu_count":       basetypes.Int64Type{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"memory_size_gi_b": v.MemorySizeGiB,
			"vcpu_count":       v.VcpuCount,
		})

	return objVal, diags
}

func (v NodeConfigurationValue) Equal(o attr.Value) bool {
	other, ok := o.(NodeConfigurationValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.MemorySizeGiB.Equal(other.MemorySizeGiB) {
		return false
	}

	if !v.VcpuCount.Equal(other.VcpuCount) {
		return false
	}

	return true
}

func (v NodeConfigurationValue) Type(ctx context.Context) attr.Type {
	return NodeConfigurationType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v NodeConfigurationValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"memory_size_gi_b": basetypes.Int64Type{},
		"vcpu_count":       basetypes.Int64Type{},
	}
}

var _ basetypes.ObjectTypable = StatusType{}

type StatusType struct {
	basetypes.ObjectType
}

func (t StatusType) Equal(o attr.Type) bool {
	other, ok := o.(StatusType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t StatusType) String() string {
	return "StatusType"
}

func (t StatusType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	messageAttribute, ok := attributes["message"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`message is missing from object`)

		return nil, diags
	}

	messageVal, ok := messageAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`message expected to be basetypes.StringValue, was: %T`, messageAttribute))
	}

	stateAttribute, ok := attributes["state"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`state is missing from object`)

		return nil, diags
	}

	stateVal, ok := stateAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`state expected to be basetypes.StringValue, was: %T`, stateAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return StatusValue{
		Message: messageVal,
		State:   stateVal,
		state:   attr.ValueStateKnown,
	}, diags
}

func NewStatusValueNull() StatusValue {
	return StatusValue{
		state: attr.ValueStateNull,
	}
}

func NewStatusValueUnknown() StatusValue {
	return StatusValue{
		state: attr.ValueStateUnknown,
	}
}

func NewStatusValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (StatusValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing StatusValue Attribute Value",
				"While creating a StatusValue value, a missing attribute value was detected. "+
					"A StatusValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("StatusValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid StatusValue Attribute Type",
				"While creating a StatusValue value, an invalid attribute value was detected. "+
					"A StatusValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("StatusValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("StatusValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra StatusValue Attribute Value",
				"While creating a StatusValue value, an extra attribute value was detected. "+
					"A StatusValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra StatusValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewStatusValueUnknown(), diags
	}

	messageAttribute, ok := attributes["message"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`message is missing from object`)

		return NewStatusValueUnknown(), diags
	}

	messageVal, ok := messageAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`message expected to be basetypes.StringValue, was: %T`, messageAttribute))
	}

	stateAttribute, ok := attributes["state"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`state is missing from object`)

		return NewStatusValueUnknown(), diags
	}

	stateVal, ok := stateAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`state expected to be basetypes.StringValue, was: %T`, stateAttribute))
	}

	if diags.HasError() {
		return NewStatusValueUnknown(), diags
	}

	return StatusValue{
		Message: messageVal,
		State:   stateVal,
		state:   attr.ValueStateKnown,
	}, diags
}

func NewStatusValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) StatusValue {
	object, diags := NewStatusValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewStatusValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t StatusType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewStatusValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewStatusValueUnknown(), nil
	}

	if in.IsNull() {
		return NewStatusValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewStatusValueMust(StatusValue{}.AttributeTypes(ctx), attributes), nil
}

func (t StatusType) ValueType(ctx context.Context) attr.Value {
	return StatusValue{}
}

var _ basetypes.ObjectValuable = StatusValue{}

type StatusValue struct {
	Message basetypes.StringValue `tfsdk:"message"`
	State   basetypes.StringValue `tfsdk:"state"`
	state   attr.ValueState
}

func (v StatusValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["message"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["state"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Message.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["message"] = val

		val, err = v.State.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["state"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v StatusValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v StatusValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v StatusValue) String() string {
	return "StatusValue"
}

func (v StatusValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"message": basetypes.StringType{},
		"state":   basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"message": v.Message,
			"state":   v.State,
		})

	return objVal, diags
}

func (v StatusValue) Equal(o attr.Value) bool {
	other, ok := o.(StatusValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Message.Equal(other.Message) {
		return false
	}

	if !v.State.Equal(other.State) {
		return false
	}

	return true
}

func (v StatusValue) Type(ctx context.Context) attr.Type {
	return StatusType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v StatusValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"message": basetypes.StringType{},
		"state":   basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = VolumeType{}

type VolumeType struct {
	basetypes.ObjectType
}

func (t VolumeType) Equal(o attr.Type) bool {
	other, ok := o.(VolumeType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t VolumeType) String() string {
	return "VolumeType"
}

func (t VolumeType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	sizeGiBAttribute, ok := attributes["size_gi_b"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`size_gi_b is missing from object`)

		return nil, diags
	}

	sizeGiBVal, ok := sizeGiBAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`size_gi_b expected to be basetypes.Int64Value, was: %T`, sizeGiBAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return nil, diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return VolumeValue{
		SizeGiB:    sizeGiBVal,
		VolumeType: typeVal,
		state:      attr.ValueStateKnown,
	}, diags
}

func NewVolumeValueNull() VolumeValue {
	return VolumeValue{
		state: attr.ValueStateNull,
	}
}

func NewVolumeValueUnknown() VolumeValue {
	return VolumeValue{
		state: attr.ValueStateUnknown,
	}
}

func NewVolumeValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (VolumeValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing VolumeValue Attribute Value",
				"While creating a VolumeValue value, a missing attribute value was detected. "+
					"A VolumeValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("VolumeValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid VolumeValue Attribute Type",
				"While creating a VolumeValue value, an invalid attribute value was detected. "+
					"A VolumeValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("VolumeValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("VolumeValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra VolumeValue Attribute Value",
				"While creating a VolumeValue value, an extra attribute value was detected. "+
					"A VolumeValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra VolumeValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewVolumeValueUnknown(), diags
	}

	sizeGiBAttribute, ok := attributes["size_gi_b"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`size_gi_b is missing from object`)

		return NewVolumeValueUnknown(), diags
	}

	sizeGiBVal, ok := sizeGiBAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`size_gi_b expected to be basetypes.Int64Value, was: %T`, sizeGiBAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return NewVolumeValueUnknown(), diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return NewVolumeValueUnknown(), diags
	}

	return VolumeValue{
		SizeGiB:    sizeGiBVal,
		VolumeType: typeVal,
		state:      attr.ValueStateKnown,
	}, diags
}

func NewVolumeValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) VolumeValue {
	object, diags := NewVolumeValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewVolumeValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t VolumeType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewVolumeValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewVolumeValueUnknown(), nil
	}

	if in.IsNull() {
		return NewVolumeValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewVolumeValueMust(VolumeValue{}.AttributeTypes(ctx), attributes), nil
}

func (t VolumeType) ValueType(ctx context.Context) attr.Value {
	return VolumeValue{}
}

var _ basetypes.ObjectValuable = VolumeValue{}

type VolumeValue struct {
	SizeGiB    basetypes.Int64Value  `tfsdk:"size_gi_b"`
	VolumeType basetypes.StringValue `tfsdk:"type"`
	state      attr.ValueState
}

func (v VolumeValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["size_gi_b"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["type"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.SizeGiB.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["size_gi_b"] = val

		val, err = v.VolumeType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["type"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v VolumeValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v VolumeValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v VolumeValue) String() string {
	return "VolumeValue"
}

func (v VolumeValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"size_gi_b": basetypes.Int64Type{},
		"type":      basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"size_gi_b": v.SizeGiB,
			"type":      v.VolumeType,
		})

	return objVal, diags
}

func (v VolumeValue) Equal(o attr.Value) bool {
	other, ok := o.(VolumeValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.SizeGiB.Equal(other.SizeGiB) {
		return false
	}

	if !v.VolumeType.Equal(other.VolumeType) {
		return false
	}

	return true
}

func (v VolumeValue) Type(ctx context.Context) attr.Type {
	return VolumeType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v VolumeValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"size_gi_b": basetypes.Int64Type{},
		"type":      basetypes.StringType{},
	}
}
