stages:
  - test
  - release

test:
  image:
    name: alpine
  stage: test
  before_script:
    - apk --no-cache add curl
  variables:
    GITLAB_TOKEN: $GITLAB_TOKEN
  script: |
    echo "$GITLAB_TOKEN"
    echo "$CI_API_V4_URL"
    echo "$CI_PROJECT_ID"
    curl --header "Private-Token: $GITLAB_TOKEN" $CI_API_V4_URL/projects/$CI_PROJECT_ID/releases

release:
  stage: release
  image:
    name: goreleaser/goreleaser
    entrypoint: ['']
  only:
    - tags
  variables:
    # Disable shallow cloning so that goreleaser can diff between tags to
    # generate a changelog.
    GIT_DEPTH: 0
    GITLAB_TOKEN: $GITLAB_TOKEN
  script:
    - goreleaser --debug release --clean