stages:
  - test
  - release

test:
  image:
    name: alpine
  stage: test
  before_script:
    - apk --no-cache add curl
  script: |
    curl --header "Private-Token: $GITLAB_TOKEN" https://gitlab.numspot.cloud/api/v4/projects/$CI_PROJECT_ID/releases

release:
  stage: release
  image:
    name: goreleaser/goreleaser
    entrypoint: ['']
  only:
    - tags
  variables:
    # Disable shallow cloning so that goreleaser can diff between tags to
    # generate a changelog.
    GIT_DEPTH: 0
    GITLAB_TOKEN: $GITLAB_TOKEN
  script:
    - goreleaser --debug release --clean