stages:
  - test
  - release

test:
  image: golang:1.20.10
  before_script:
    - go mod download
  variables:
    TF_ACC: "1"
  script:
    - go test ./...

release:
  stage: release
  image:
    name: goreleaser/goreleaser
    entrypoint: ['']
  only:
    - tags
  variables:
    # Disable shallow cloning so that goreleaser can diff between tags to
    # generate a changelog.
    GIT_DEPTH: 0
    GITLAB_TOKEN: $CI_JOB_TOKEN
    COSIGN_KEY: $COSIGN_KEY
  script:
    - goreleaser --debug release --clean