include:
  - remote: 'https://api.r2devops.numspot.dev/job/r/gitlab/cloud/ci-templates/jobs/go_lint@0.3.0.yaml'
  - remote: 'https://api.r2devops.numspot.dev/job/r/gitlab/cloud/ci-templates/jobs/go_unit-tests@0.1.0.yaml'

go_lint:
  rules:
    - if: $CI_PIPELINE_SOURCE != "schedule"

go_unit-tests:
  rules:
    - if: $CI_PIPELINE_SOURCE != "schedule"

acc-tests:
  image: golang:1.20.10
  stage: test
  before_script:
    - go mod download
  variables:
    NUMSPOT_API_HOST: $NUMSPOT_API_HOST
    NUMSPOT_IAM_HOST: $NUMSPOT_IAM_HOST
    NUMSPOT_CLIENT_ID: $NUMSPOT_CLIENT_ID
    NUMSPOT_CLIENT_SECRET: $NUMSPOT_CLIENT_SECRET
    NUMSPOT_SPACE_ID: $NUMSPOT_SPACE_ID
    TF_ACC: "1"
  script:
    - go test ./...
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"