include:
  - project: 'cloud/ci-templates'
    ref: 'jobs/go_unit-tests@0.2.2'
    file: 'jobs/go_unit-tests/go_unit-tests.yml'

variables:
  GOPRIVATE: gitlab.numspot.cloud/*
before_script:
  - echo "machine ${CI_SERVER_HOST} login gitlab-ci-token password
    ${CI_JOB_TOKEN}" > ~/.netrc

go_lint:
  image: golangci/golangci-lint:v1.57.1-alpine
  stage: test
  script:
    - golangci-lint run --out-format code-climate:gl-code-quality-report.json,line-number --timeout=10m
  artifacts:
    when: always
    expire_in: 1 month
    reports:
      codequality: gl-code-quality-report.json
    paths:
      - gl-code-quality-report.json
  rules:
    - if: $CI_PIPELINE_SOURCE != "schedule"

go_unit-tests:
  rules:
    - if: $CI_PIPELINE_SOURCE != "schedule"

acc-tests:
  image: golang:1.20.10
  stage: test
  before_script:
    - go mod download
  variables:
    NUMSPOT_API_HOST: $NUMSPOT_API_HOST
    NUMSPOT_IAM_HOST: $NUMSPOT_IAM_HOST
    NUMSPOT_CLIENT_ID: $NUMSPOT_CLIENT_ID
    NUMSPOT_CLIENT_SECRET: $NUMSPOT_CLIENT_SECRET
    NUMSPOT_SPACE_ID: $NUMSPOT_SPACE_ID
    TF_ACC: "1"
  script:
    - go test ./...
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"