workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE != "merge_request_event"
include:
  - project: 'cloud/ci-templates'
    ref: 'jobs/go_unit-tests@0.2.2'
    file: 'jobs/go_unit-tests/go_unit-tests.yml'

variables:
  GOPRIVATE: gitlab.numspot.cloud/*
before_script:
  - echo "machine ${CI_SERVER_HOST} login gitlab-ci-token password
    ${CI_JOB_TOKEN}" > ~/.netrc

go_lint:
  image: golangci/golangci-lint:v1.57.1-alpine
  stage: test
  script:
    - golangci-lint run --out-format code-climate:gl-code-quality-report.json,line-number --timeout=10m
  artifacts:
    when: always
    expire_in: 1 month
    reports:
      codequality: gl-code-quality-report.json
    paths:
      - gl-code-quality-report.json
  rules:
    - if: $CI_PIPELINE_SOURCE != "schedule"

go_unit-tests:
  rules:
    - if: $CI_PIPELINE_SOURCE != "schedule"

acc-tests:
  image: golang:1.21.0
  stage: test
  before_script:
    - echo "machine ${CI_SERVER_HOST} login gitlab-ci-token password
      ${CI_JOB_TOKEN}" > ~/.netrc
    - go mod download
    - go install gotest.tools/gotestsum@latest
  variables:
    NUMSPOT_API_HOST: $NUMSPOT_API_HOST
    NUMSPOT_IAM_HOST: $NUMSPOT_IAM_HOST
    NUMSPOT_CLIENT_ID: $NUMSPOT_CLIENT_ID
    NUMSPOT_CLIENT_SECRET: $NUMSPOT_CLIENT_SECRET
    NUMSPOT_SPACE_ID: $NUMSPOT_SPACE_ID
    TF_ACC: "1"
  script:
    - gotestsum --junitfile acc-tests-report.xml --format testname -- --tags=acc ./...
  artifacts:
    when: always
    reports:
      junit: acc-tests-report.xml
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"

push_to_github:
  stage: deploy
  image: alpine/git
  before_script:
    - 'which ssh-agent || ( apk add openssh-client )'
    - eval $(ssh-agent -s)
    - echo "$GITHUB_DEPLOY_KEY" | ssh-add -
    - mkdir -p ~/.ssh
    - 'echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - git remote add github git@github.com:numspot/terraform-provider-numspot.git
    - git push github HEAD:main
    - git push github HEAD:main --tags
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_COMMIT_TAG'