version: "2"

issues:
  max-same-issues: 0

linters:
  disable:
    - staticcheck
  enable:
    - durationcheck
    - errcheck
    - forcetypeassert
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - unconvert
    - unparam
    - unused
  exclusions:
    generated: strict

run:
  # Prevent false positive timeouts in CI
  timeout: 5m