# Visit https://goreleaser.com for documentation on how to customize this
# behavior.
before:
  hooks:
    # this is just an example and not a requirement for provider building/publishing
    - go mod tidy
gitlab_urls:
  api: "{{ .Env.CI_API_V4_URL }}"
  download: https://gitlab.numspot.cloud

  # set to true if you use a self-signed certificate
  # skip_tls_verify: false

  # set to true if you want to upload to the Package Registry rather than attachments
  # Only works with GitLab 13.5+
  #
  # Since: v1.3
  use_package_registry: true

  # Set this if you set GITLAB_TOKEN to the value of CI_JOB_TOKEN.
  #
  # Since: v1.11
  use_job_token: true
builds:
- env:
    # goreleaser does not work with CGO, it could also complicate
    # usage by users in CI/CD systems like Terraform Cloud where
    # they are unable to install libraries.
    - CGO_ENABLED=0
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
    - -trimpath
  ldflags:
    - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
  goos:
    - freebsd
    - windows
    - linux
    - darwin
  goarch:
    - amd64
    - '386'
    - arm
    - arm64
  ignore:
    - goos: darwin
      goarch: '386'
  binary: '{{ .ProjectName }}_v{{ .Version }}'
archives:
- format: zip
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
checksum:
  extra_files:
    - glob: 'terraform-registry-manifest.json'
      name_template: '{{ .ProjectName }}_{{ .Version }}_manifest.json'
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
#signs:
#  - artifacts: checksum
#    args:
#      # if you are using this in a GitHub action or some other automated pipeline, you
#      # need to pass the batch flag to indicate its not interactive.
#      - "--batch"
#      - "--local-user"
#      - "{{ .Env.GPG_FINGERPRINT }}" # set this environment variable for your signing key
#      - "--output"
#      - "${signature}"
#      - "--detach-sign"
#      - "${artifact}"
release:
  # gitlab:
  #   name: 168 # Use repository ID to prevent usage of the repository name
  extra_files:
    - glob: 'terraform-registry-manifest.json'
      name_template: '{{ .ProjectName }}_{{ .Version }}_manifest.json'
  # If you want to manually examine the release before its live, uncomment this line:
  # draft: true
changelog:
  skip: true
