// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_bucket

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func BucketResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "The name of the Bucket.",
				MarkdownDescription: "The name of the Bucket.",
			},
		},
	}
}

type BucketModel struct {
	Name types.String `tfsdk:"name"`
}
