// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider_numspot

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

func NumspotProviderSchema(ctx context.Context) schema.Schema {
	return schema.Schema{}
}

type NumspotModel struct {
}
