// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_public_ip

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"gitlab.numspot.cloud/cloud/terraform-provider-numspot/internal/provider/tags"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func PublicIpResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "The allocation ID of the public IP.",
				MarkdownDescription: "The allocation ID of the public IP.",
			},
			"nic_id": schema.StringAttribute{
				Computed:            true,
				Optional:            true,
				Description:         "The ID of the NIC the public IP is associated with (if any).",
				MarkdownDescription: "The ID of the NIC the public IP is associated with (if any).",
				Validators: []validator.String{
					stringvalidator.ConflictsWith(path.MatchRoot("vm_id")),
				},
			},
			"private_ip": schema.StringAttribute{
				Computed:            true,
				Description:         "The private IP associated with the public IP.",
				MarkdownDescription: "The private IP associated with the public IP.",
			},
			"public_ip": schema.StringAttribute{
				Computed:            true,
				Description:         "The public IP.",
				MarkdownDescription: "The public IP.",
			},
			"vm_id": schema.StringAttribute{
				Optional:            true,
				Description:         "The ID of the VM the public IP is associated with (if any).",
				MarkdownDescription: "The ID of the VM the public IP is associated with (if any).",
				Validators: []validator.String{
					stringvalidator.ConflictsWith(path.MatchRoot("nic_id")),
				},
			},
			"link_public_ip": schema.StringAttribute{
				Computed:            true,
				Description:         "The ID of the association between the public IP and VM/NIC (if any).",
				MarkdownDescription: "The ID of the association between the public IP and VM/NIC (if any).",
			},
			"tags": tags.TagsSchema(ctx),
		},
	}
}

type PublicIpModel struct {
	Id           types.String `tfsdk:"id"`
	NicId        types.String `tfsdk:"nic_id"`
	PrivateIp    types.String `tfsdk:"private_ip"`
	PublicIp     types.String `tfsdk:"public_ip"`
	VmId         types.String `tfsdk:"vm_id"`
	LinkPublicIP types.String `tfsdk:"link_public_ip"`
	Tags         types.List   `tfsdk:"tags"`
}
