// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package virtualgateway

import (
	"context"
	"gitlab.numspot.cloud/cloud/terraform-provider-numspot/internal/services/tags"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func VirtualGatewayResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"connection_type": schema.StringAttribute{
				Required:            true,
				Description:         "The type of VPN connection supported by the virtual gateway (only `ipsec.1` is supported).",
				MarkdownDescription: "The type of VPN connection supported by the virtual gateway (only `ipsec.1` is supported).",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "The ID of the virtual gateway.",
				MarkdownDescription: "The ID of the virtual gateway.",
			},
			"vpc_id": schema.StringAttribute{
				Computed:            true,
				Optional:            true,
				Description:         "The ID of the Net to which the virtual gateway is attached.",
				MarkdownDescription: "The ID of the Net to which the virtual gateway is attached.",
			},
			"state": schema.StringAttribute{
				Computed:            true,
				Description:         "The state of the virtual gateway (`pending` \\| `available` \\| `deleting` \\| `deleted`).",
				MarkdownDescription: "The state of the virtual gateway (`pending` \\| `available` \\| `deleting` \\| `deleted`).",
			},
			"tags": tags.TagsSchema(ctx),
		},
		DeprecationMessage: "Managing IAAS services with Terraform is deprecated",
	}
}
