// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package vpcpeering

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"gitlab.numspot.cloud/cloud/terraform-provider-numspot/internal/services/tags"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
)

func VpcPeeringResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"accepter_vpc": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"ip_range": schema.StringAttribute{
						Computed:            true,
						Description:         "The IP range for the accepter Net, in CIDR notation (for example, `10.0.0.0/16`).",
						MarkdownDescription: "The IP range for the accepter Net, in CIDR notation (for example, `10.0.0.0/16`).",
					},
					"vpc_id": schema.StringAttribute{
						Computed:            true,
						Description:         "The ID of the accepter Vpc.",
						MarkdownDescription: "The ID of the accepter Vpc.",
					},
				},
				CustomType: AccepterVpcType{
					ObjectType: types.ObjectType{
						AttrTypes: AccepterVpcValue{}.AttributeTypes(ctx),
					},
				},
				Computed:            true,
				Description:         "Information about the accepter Vpc.",
				MarkdownDescription: "Information about the accepter Vpc.",
			},
			"accepter_vpc_id": schema.StringAttribute{
				Required:            true,
				Description:         "The ID of the Vpc you want to connect with.",
				MarkdownDescription: "The ID of the Vpc you want to connect with.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"expiration_date": schema.StringAttribute{
				Computed:            true,
				Description:         "The date and time at which the Vpc peerings expire.",
				MarkdownDescription: "The date and time at which the Vpc peerings expire.",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "The ID of the Vpc peering.",
				MarkdownDescription: "The ID of the Vpc peering.",
			},
			"source_vpc": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"ip_range": schema.StringAttribute{
						Computed:            true,
						Description:         "The IP range for the source Net, in CIDR notation (for example, `10.0.0.0/16`).",
						MarkdownDescription: "The IP range for the source Net, in CIDR notation (for example, `10.0.0.0/16`).",
					},
					"vpc_id": schema.StringAttribute{
						Computed:            true,
						Description:         "The ID of the source Vpc.",
						MarkdownDescription: "The ID of the source Vpc.",
					},
				},
				CustomType: SourceVpcType{
					ObjectType: types.ObjectType{
						AttrTypes: SourceVpcValue{}.AttributeTypes(ctx),
					},
				},
				Computed:            true,
				Description:         "Information about the source Vpc.",
				MarkdownDescription: "Information about the source Vpc.",
			},
			"source_vpc_id": schema.StringAttribute{
				Required:            true,
				Description:         "The ID of the Vpc you send the peering request from.",
				MarkdownDescription: "The ID of the Vpc you send the peering request from.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"state": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"message": schema.StringAttribute{
						Computed:            true,
						Description:         "Additional information about the state of the Vpc peering.",
						MarkdownDescription: "Additional information about the state of the Vpc peering.",
					},
					"name": schema.StringAttribute{
						Computed:            true,
						Description:         "The state of the Vpc peering (`pending-acceptance` \\| `active` \\| `rejected` \\| `failed` \\| `expired` \\| `deleted`).",
						MarkdownDescription: "The state of the Vpc peering (`pending-acceptance` \\| `active` \\| `rejected` \\| `failed` \\| `expired` \\| `deleted`).",
					},
				},
				CustomType: StateType{
					ObjectType: types.ObjectType{
						AttrTypes: StateValue{}.AttributeTypes(ctx),
					},
				},
				Computed:            true,
				Description:         "Information about the state of the Vpc peering.",
				MarkdownDescription: "Information about the state of the Vpc peering.",
			},
			"tags": tags.TagsSchema(ctx),
		},
		DeprecationMessage: "Managing IAAS services with Terraform is deprecated",
	}
}

type VpcPeeringModel struct {
	AccepterVpc    AccepterVpcValue `tfsdk:"accepter_vpc"`
	AccepterVpcId  types.String     `tfsdk:"accepter_vpc_id"`
	ExpirationDate types.String     `tfsdk:"expiration_date"`
	Id             types.String     `tfsdk:"id"`
	SourceVpc      SourceVpcValue   `tfsdk:"source_vpc"`
	SourceVpcId    types.String     `tfsdk:"source_vpc_id"`
	State          StateValue       `tfsdk:"state"`
	Tags           types.List       `tfsdk:"tags"`
}

var _ basetypes.ObjectTypable = AccepterVpcType{}

type AccepterVpcType struct {
	basetypes.ObjectType
}

func (t AccepterVpcType) Equal(o attr.Type) bool {
	other, ok := o.(AccepterVpcType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t AccepterVpcType) String() string {
	return "AccepterVpcType"
}

func (t AccepterVpcType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	ipRangeAttribute, ok := attributes["ip_range"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ip_range is missing from object`)

		return nil, diags
	}

	ipRangeVal, ok := ipRangeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ip_range expected to be basetypes.StringValue, was: %T`, ipRangeAttribute))
	}

	vpcIdAttribute, ok := attributes["vpc_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`vpc_id is missing from object`)

		return nil, diags
	}

	vpcIdVal, ok := vpcIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`vpc_id expected to be basetypes.StringValue, was: %T`, vpcIdAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return AccepterVpcValue{
		IpRange: ipRangeVal,
		VpcId:   vpcIdVal,
		state:   attr.ValueStateKnown,
	}, diags
}

func NewAccepterVpcValueNull() AccepterVpcValue {
	return AccepterVpcValue{
		state: attr.ValueStateNull,
	}
}

func NewAccepterVpcValueUnknown() AccepterVpcValue {
	return AccepterVpcValue{
		state: attr.ValueStateUnknown,
	}
}

func NewAccepterVpcValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (AccepterVpcValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing AccepterVpcValue Attribute Value",
				"While creating a AccepterVpcValue value, a missing attribute value was detected. "+
					"A AccepterVpcValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("AccepterVpcValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid AccepterVpcValue Attribute Type",
				"While creating a AccepterVpcValue value, an invalid attribute value was detected. "+
					"A AccepterVpcValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("AccepterVpcValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("AccepterVpcValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra AccepterVpcValue Attribute Value",
				"While creating a AccepterVpcValue value, an extra attribute value was detected. "+
					"A AccepterVpcValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra AccepterVpcValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewAccepterVpcValueUnknown(), diags
	}

	ipRangeAttribute, ok := attributes["ip_range"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ip_range is missing from object`)

		return NewAccepterVpcValueUnknown(), diags
	}

	ipRangeVal, ok := ipRangeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ip_range expected to be basetypes.StringValue, was: %T`, ipRangeAttribute))
	}

	vpcIdAttribute, ok := attributes["vpc_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`vpc_id is missing from object`)

		return NewAccepterVpcValueUnknown(), diags
	}

	vpcIdVal, ok := vpcIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`vpc_id expected to be basetypes.StringValue, was: %T`, vpcIdAttribute))
	}

	if diags.HasError() {
		return NewAccepterVpcValueUnknown(), diags
	}

	return AccepterVpcValue{
		IpRange: ipRangeVal,
		VpcId:   vpcIdVal,
		state:   attr.ValueStateKnown,
	}, diags
}

func NewAccepterVpcValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) AccepterVpcValue {
	object, diags := NewAccepterVpcValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewAccepterVpcValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t AccepterVpcType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewAccepterVpcValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewAccepterVpcValueUnknown(), nil
	}

	if in.IsNull() {
		return NewAccepterVpcValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewAccepterVpcValueMust(AccepterVpcValue{}.AttributeTypes(ctx), attributes), nil
}

func (t AccepterVpcType) ValueType(ctx context.Context) attr.Value {
	return AccepterVpcValue{}
}

var _ basetypes.ObjectValuable = AccepterVpcValue{}

type AccepterVpcValue struct {
	IpRange basetypes.StringValue `tfsdk:"ip_range"`
	VpcId   basetypes.StringValue `tfsdk:"vpc_id"`
	state   attr.ValueState
}

func (v AccepterVpcValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["ip_range"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["vpc_id"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.IpRange.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["ip_range"] = val

		val, err = v.VpcId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["vpc_id"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v AccepterVpcValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v AccepterVpcValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v AccepterVpcValue) String() string {
	return "AccepterVpcValue"
}

func (v AccepterVpcValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	objVal, diags := types.ObjectValue(
		map[string]attr.Type{
			"ip_range": basetypes.StringType{},
			"vpc_id":   basetypes.StringType{},
		},
		map[string]attr.Value{
			"ip_range": v.IpRange,
			"vpc_id":   v.VpcId,
		})

	return objVal, diags
}

func (v AccepterVpcValue) Equal(o attr.Value) bool {
	other, ok := o.(AccepterVpcValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.IpRange.Equal(other.IpRange) {
		return false
	}

	if !v.VpcId.Equal(other.VpcId) {
		return false
	}

	return true
}

func (v AccepterVpcValue) Type(ctx context.Context) attr.Type {
	return AccepterVpcType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v AccepterVpcValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"ip_range": basetypes.StringType{},
		"vpc_id":   basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = SourceVpcType{}

type SourceVpcType struct {
	basetypes.ObjectType
}

func (t SourceVpcType) Equal(o attr.Type) bool {
	other, ok := o.(SourceVpcType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t SourceVpcType) String() string {
	return "SourceVpcType"
}

func (t SourceVpcType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	ipRangeAttribute, ok := attributes["ip_range"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ip_range is missing from object`)

		return nil, diags
	}

	ipRangeVal, ok := ipRangeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ip_range expected to be basetypes.StringValue, was: %T`, ipRangeAttribute))
	}

	vpcIdAttribute, ok := attributes["vpc_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`vpc_id is missing from object`)

		return nil, diags
	}

	vpcIdVal, ok := vpcIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`vpc_id expected to be basetypes.StringValue, was: %T`, vpcIdAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return SourceVpcValue{
		IpRange: ipRangeVal,
		VpcId:   vpcIdVal,
		state:   attr.ValueStateKnown,
	}, diags
}

func NewSourceVpcValueNull() SourceVpcValue {
	return SourceVpcValue{
		state: attr.ValueStateNull,
	}
}

func NewSourceVpcValueUnknown() SourceVpcValue {
	return SourceVpcValue{
		state: attr.ValueStateUnknown,
	}
}

func NewSourceVpcValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (SourceVpcValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing SourceVpcValue Attribute Value",
				"While creating a SourceVpcValue value, a missing attribute value was detected. "+
					"A SourceVpcValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("SourceVpcValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid SourceVpcValue Attribute Type",
				"While creating a SourceVpcValue value, an invalid attribute value was detected. "+
					"A SourceVpcValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("SourceVpcValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("SourceVpcValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra SourceVpcValue Attribute Value",
				"While creating a SourceVpcValue value, an extra attribute value was detected. "+
					"A SourceVpcValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra SourceVpcValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewSourceVpcValueUnknown(), diags
	}

	ipRangeAttribute, ok := attributes["ip_range"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ip_range is missing from object`)

		return NewSourceVpcValueUnknown(), diags
	}

	ipRangeVal, ok := ipRangeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ip_range expected to be basetypes.StringValue, was: %T`, ipRangeAttribute))
	}

	vpcIdAttribute, ok := attributes["vpc_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`vpc_id is missing from object`)

		return NewSourceVpcValueUnknown(), diags
	}

	vpcIdVal, ok := vpcIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`vpc_id expected to be basetypes.StringValue, was: %T`, vpcIdAttribute))
	}

	if diags.HasError() {
		return NewSourceVpcValueUnknown(), diags
	}

	return SourceVpcValue{
		IpRange: ipRangeVal,
		VpcId:   vpcIdVal,
		state:   attr.ValueStateKnown,
	}, diags
}

func NewSourceVpcValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) SourceVpcValue {
	object, diags := NewSourceVpcValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewSourceVpcValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t SourceVpcType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewSourceVpcValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewSourceVpcValueUnknown(), nil
	}

	if in.IsNull() {
		return NewSourceVpcValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewSourceVpcValueMust(SourceVpcValue{}.AttributeTypes(ctx), attributes), nil
}

func (t SourceVpcType) ValueType(ctx context.Context) attr.Value {
	return SourceVpcValue{}
}

var _ basetypes.ObjectValuable = SourceVpcValue{}

type SourceVpcValue struct {
	IpRange basetypes.StringValue `tfsdk:"ip_range"`
	VpcId   basetypes.StringValue `tfsdk:"vpc_id"`
	state   attr.ValueState
}

func (v SourceVpcValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["ip_range"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["vpc_id"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.IpRange.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["ip_range"] = val

		val, err = v.VpcId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["vpc_id"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v SourceVpcValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v SourceVpcValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v SourceVpcValue) String() string {
	return "SourceVpcValue"
}

func (v SourceVpcValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	objVal, diags := types.ObjectValue(
		map[string]attr.Type{
			"ip_range": basetypes.StringType{},
			"vpc_id":   basetypes.StringType{},
		},
		map[string]attr.Value{
			"ip_range": v.IpRange,
			"vpc_id":   v.VpcId,
		})

	return objVal, diags
}

func (v SourceVpcValue) Equal(o attr.Value) bool {
	other, ok := o.(SourceVpcValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.IpRange.Equal(other.IpRange) {
		return false
	}

	if !v.VpcId.Equal(other.VpcId) {
		return false
	}

	return true
}

func (v SourceVpcValue) Type(ctx context.Context) attr.Type {
	return SourceVpcType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v SourceVpcValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"ip_range": basetypes.StringType{},
		"vpc_id":   basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = StateType{}

type StateType struct {
	basetypes.ObjectType
}

func (t StateType) Equal(o attr.Type) bool {
	other, ok := o.(StateType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t StateType) String() string {
	return "StateType"
}

func (t StateType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	messageAttribute, ok := attributes["message"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`message is missing from object`)

		return nil, diags
	}

	messageVal, ok := messageAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`message expected to be basetypes.StringValue, was: %T`, messageAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return StateValue{
		Message: messageVal,
		Name:    nameVal,
		state:   attr.ValueStateKnown,
	}, diags
}

func NewStateValueNull() StateValue {
	return StateValue{
		state: attr.ValueStateNull,
	}
}

func NewStateValueUnknown() StateValue {
	return StateValue{
		state: attr.ValueStateUnknown,
	}
}

func NewStateValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (StateValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing StateValue Attribute Value",
				"While creating a StateValue value, a missing attribute value was detected. "+
					"A StateValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("StateValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid StateValue Attribute Type",
				"While creating a StateValue value, an invalid attribute value was detected. "+
					"A StateValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("StateValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("StateValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra StateValue Attribute Value",
				"While creating a StateValue value, an extra attribute value was detected. "+
					"A StateValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra StateValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewStateValueUnknown(), diags
	}

	messageAttribute, ok := attributes["message"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`message is missing from object`)

		return NewStateValueUnknown(), diags
	}

	messageVal, ok := messageAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`message expected to be basetypes.StringValue, was: %T`, messageAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewStateValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	if diags.HasError() {
		return NewStateValueUnknown(), diags
	}

	return StateValue{
		Message: messageVal,
		Name:    nameVal,
		state:   attr.ValueStateKnown,
	}, diags
}

func NewStateValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) StateValue {
	object, diags := NewStateValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewStateValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t StateType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewStateValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewStateValueUnknown(), nil
	}

	if in.IsNull() {
		return NewStateValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewStateValueMust(StateValue{}.AttributeTypes(ctx), attributes), nil
}

func (t StateType) ValueType(ctx context.Context) attr.Value {
	return StateValue{}
}

var _ basetypes.ObjectValuable = StateValue{}

type StateValue struct {
	Message basetypes.StringValue `tfsdk:"message"`
	Name    basetypes.StringValue `tfsdk:"name"`
	state   attr.ValueState
}

func (v StateValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["message"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Message.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["message"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v StateValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v StateValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v StateValue) String() string {
	return "StateValue"
}

func (v StateValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	objVal, diags := types.ObjectValue(
		map[string]attr.Type{
			"message": basetypes.StringType{},
			"name":    basetypes.StringType{},
		},
		map[string]attr.Value{
			"message": v.Message,
			"name":    v.Name,
		})

	return objVal, diags
}

func (v StateValue) Equal(o attr.Value) bool {
	other, ok := o.(StateValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Message.Equal(other.Message) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	return true
}

func (v StateValue) Type(ctx context.Context) attr.Type {
	return StateType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v StateValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"message": basetypes.StringType{},
		"name":    basetypes.StringType{},
	}
}
